apiVersion: tags.gcp.upbound.io/v1beta1
kind: LocationTagBinding
metadata:
  annotations:
    meta.upbound.io/example-id: tags/v1beta1/locationtagbinding
  labels:
    testing.upbound.io/example-name: binding
  name: binding
spec:
  forProvider:
    location: us-central1
    parent: //run.googleapis.com/projects/1234567890/locations/us-central1/services/default
    tagValueSelector:
      matchLabels:
        testing.upbound.io/example-name: value

---

apiVersion: cloudrun.gcp.upbound.io/v1beta1
kind: V2Service
metadata:
  annotations:
    meta.upbound.io/example-id: tags/v1beta1/locationtagbinding
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    ingress: "INGRESS_TRAFFIC_ALL"
    location: us-central1
    template:
    - containers:
      - image: us-docker.pkg.dev/cloudrun/container/hello

---

apiVersion: tags.gcp.upbound.io/v1beta1
kind: TagKey
metadata:
  annotations:
    meta.upbound.io/example-id: tags/v1beta1/locationtagbinding
  labels:
    testing.upbound.io/example-name: key
  name: key
spec:
  forProvider:
    description: For keyname resources.
    parent: projects/1234567890
    shortName: keyname

---

apiVersion: tags.gcp.upbound.io/v1beta1
kind: TagValue
metadata:
  annotations:
    meta.upbound.io/example-id: tags/v1beta1/locationtagbinding
  labels:
    testing.upbound.io/example-name: value
  name: value
spec:
  forProvider:
    description: For valuename resources.
    parentSelector:
      matchLabels:
        testing.upbound.io/example-name: key
    shortName: valuename
